### ISSUE TITLE
Execute Script at Synology without otp

### ISSUE THREAD

**Issue by hour26** [Caleb9/SynologyPhotosAlbumList#3]
Hi, the script works great for me - great work! I would like to run it directly on my Synology via the task manager. This also works so far, except that of course it doesn't work without a new token for otp with each execution. is there a possibility to run the script with the current user, which also starts the task - but without otp. Is there a way here? Greetings Jonas

**Comment by Caleb9** [comment]
Hi Jonas, no unfortunately :(. The app works by communicating with Synology Photos API via HTTP requests. This requires that it authenticates first, and if you have MFA enabled then it has to provide your username, password and OTP. As a workaround, you can consider creating a separate user account with access only to the relevant parts of your Photos collection, disable MFA for that account and feed the app with just the username and password.

**Comment by Caleb9** [comment]
@hour26 check out the new version of this app at https://github.com/caleb9/syno-photos-util, it can do what you wanted, i.e. you can skip OTP verification with MFA enabled, and schedule the app to run periodically :). Please submit any issues in the linked repository.
